name: Tag on version.txt change

on:
  push:
    paths:
      - version.txt
    branches:
      - main  # Adjust to your default branch

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt | tr -d '[:space:]')
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "${{ steps.get_version.outputs.version }}")
          if [[ -z "$TAG_EXISTS" ]]; then
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Create tag from version.txt
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${{ steps.get_version.outputs.version }}"
          git push origin "${{ steps.get_version.outputs.version }}"
